/*some sample vectors*/
load("/Users/Foad/ownCloud/My_activities/Modern Robotics- Stefano/libs/Maxima Language/Screw.mac")$

W1:vec(1,2,4);

W2:vec(5,7,3);

W3:vec(3,9,5);

W4:vec(6,87,4);

L1:PlcFrmTwoPnt(W1,W2);

L2:PlcFrmTwoPnt(W3,W4);

FtCmnPPndclr(L1,L2);

FndClsPntLnOrg(L1);

FndClsPntLnPnt(L1,W3);

A1:vec(a[1],a[2],a[3]);

B1:vec(b[1],b[2],b[3]);

C1:vec(c[1],c[2],c[3]);

A2:Skew(A1);

B2:Skew(B1);

A2.B2;

Skew(crosprod(A1,B1));

ident(4);

zeromatrix(4,4);
